# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler
        
on: [pull_request]
name: Pull Request Status Checks

jobs:
  pRStatusGiphy:
    name: PR Status Giphy
    runs-on: ubuntu-latest
    steps:
    - name: PR Status Giphy
      uses: jzweifel/pr-status-giphy-action@master
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
